package telran.solution.dto.kafkaData.solutionDataDto;

public enum SolutionMethodName {
    ADD_SOLUTION,
    ADD_LIKE,
    REMOVE_LIKE,
    ADD_DISLIKE,
    REMOVE_DISLIKE,
    REMOVE_LIKE_REMOVE_COMMENT_ACTIVITY,
    REMOVE_LIKE_REMOVE_ALL_ACTIVITIES,
    REMOVE_DISLIKE_REMOVE_COMMENT_ACTIVITY,
    REMOVE_DISLIKE_REMOVE_ALL_ACTIVITIES,
    DELETE_SOLUTION,
    DELETE_SOLUTION_AND_PROBLEM
}
